config/routes.rb
Rails.application.routes.draw do
  
  resources :videos
  root 'welcome#index'
 
  # root 'welcome#index'
  
  devise_for :users
 # get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    has_one_attached :clip
    has_one_attached :thumbnail

    def as_json(options = {})
        super(options.merge(include: :user))
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :clip, :thumbnail)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @videos = Video.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navigation.html.erb
<div class="wrapper">
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Youtube Clone</h3>
        <strong>YT</strong>
    </div>

    <ul class="list-unstyled components">
        <li class="active">
        <%= link_to 'Home' , root_path, class: 'dropdown-toggle' %>
          
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to 'Create new video' , new_video_url, class: 'dropdown-toggle' %>
        </li>
        <% end %>
       
       
    </ul>

    
</nav>

<!-- Page Content  -->
<div id="content">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                <% if user_signed_in? %>
                <li class="nav-item active">
                      
              Welcome <%= current_user.name %>
                
            </li>
                    <li class="nav-item active">
                      
                        <%= link_to 'Logout',destroy_user_session_path, :method => :delete, class: 'nav-link' %>
                        
                    </li>
                <% else %>
                    <li class="nav-item active">
                       <%= link_to 'Register' , new_user_registration_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                    <%= link_to 'Sign in' , new_user_session_path, class: 'nav-link' %>
                      
                    </li>
                <% end %>
                   
                </ul>
            </div>
        </div>
    </nav>



    

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>


  
  <%= yield %>
  </div>
</div>


 
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :clip %>
    <%= form.file_field :clip %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', root_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />

<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="640"
    height="264"
    poster="<%=  url_for(@video.thumbnail) %>"
    data-setup="{}"
  >
    <source src="<%=  url_for(@video.clip) %>" type="video/mp4" />
   
    </p>
  </video>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', root_path %>

<script src="https://vjs.zencdn.net/7.8.4/video.js"></script>

app/views/welcome/index.html.erb
<link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />

<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
<div class="card-deck">
<% i = 0 %>
<% @videos.each do |video| %>
  <div class="card">
  <video
  id="my-video"
  class="video-js"
  controls
  preload="auto"
  width="311"
  height="260"
  poster="<%=  url_for( video.thumbnail) %>"
  data-setup="{}"
>
  <source src="<%=  url_for( video.clip) %>" type="video/mp4" />
 
  
</video>
    <div class="card-body">
    <h5 class="card-title"><%= video.title %></h5>
    <p class="card-text"><%=  video.description %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">posted by <a ng-href="#/users/{{video.user.username}}"><%=  video.user.name %></a></small>
    </div>
  </div>
  <% 
  i +=1
  %>
  
  <% if (i%3) == 0 %>
    </div>
    </br>
    <div class="card-deck">
    <% end %>
  <% end %>
  </div>


<script src="https://vjs.zencdn.net/7.8.4/video.js"></script>